export type VelmereSitePageStatus = "blocked" | "partial" | "solid" | "launch_control";
export type VelmereVercelRisk = "low" | "medium" | "high";

export type VelmereSitePageAuditItem = {
  id: string;
  route: string;
  title: string;
  area: "brand" | "commerce" | "vlm" | "shield" | "community" | "account" | "legal" | "ops";
  progress: number;
  status: VelmereSitePageStatus;
  vercelRisk: VelmereVercelRisk;
  userGoal: string;
  currentState: string;
  launchBlockers: string[];
  nextPass: string;
};

export const velmereSitePageAudit: VelmereSitePageAuditItem[] = [
  {
    id: "home",
    route: "/[locale]",
    title: "Home / brand landing",
    area: "brand",
    progress: 60,
    status: "partial",
    vercelRisk: "low",
    userGoal: "Understand Velmère in a few seconds and choose clothing, VLM access or Square without confusion.",
    currentState: "Premium shell exists, but hero hierarchy, launch CTAs and product narrative still need final polish.",
    launchBlockers: ["final hero copy", "mobile rhythm", "CTA priority", "production media"],
    nextPass: "Tighten first-screen message, reduce mixed language and connect clear paths to Clothing, Shield and Square.",
  },
  {
    id: "clothing",
    route: "/[locale]/clothing",
    title: "Clothing collection",
    area: "commerce",
    progress: 67,
    status: "solid",
    vercelRisk: "low",
    userGoal: "Browse products with clear materials, sizes, shipping expectations and trust before checkout.",
    currentState: "Product UI and truth fields are present; provider truth and final media still need launch confirmation.",
    launchBlockers: ["final SKU mapping", "provider media", "stock state", "shipping proof"],
    nextPass: "Connect final provider data and keep product cards honest about material, fit and delivery.",
  },
  {
    id: "shop",
    route: "/[locale]/shop",
    title: "Shop catalogue",
    area: "commerce",
    progress: 66,
    status: "partial",
    vercelRisk: "low",
    userGoal: "Move from browse to product detail without fake stock, fake pricing or missing delivery truth.",
    currentState: "Catalogue works as a launch-control surface, not a finished fulfilment stack.",
    launchBlockers: ["real checkout", "tax/shipping integration", "provider availability", "return policy linking"],
    nextPass: "Make every product state explicit: preview, available, sold out, provider pending or checkout disabled.",
  },
  {
    id: "product-detail",
    route: "/[locale]/shop/[id]",
    title: "Product detail pages",
    area: "commerce",
    progress: 70,
    status: "partial",
    vercelRisk: "medium",
    userGoal: "See exact product truth before buying: size, material, delivery, returns and limitations.",
    currentState: "Dynamic product details exist, but launch depends on real provider truth and checkout safety.",
    launchBlockers: ["provider SKU mapping", "size proof", "delivery estimates", "payment flow"],
    nextPass: "Audit product detail pages for every language and forbid checkout unless product truth is complete.",
  },
  {
    id: "cart-checkout",
    route: "/[locale]/cart + /[locale]/checkout",
    title: "Cart / checkout",
    area: "commerce",
    progress: 50,
    status: "launch_control",
    vercelRisk: "medium",
    userGoal: "Buy safely with correct totals, tax, shipping, delivery and return information.",
    currentState: "Checkout must remain launch-controlled until real provider/payment/order-state flows are verified.",
    launchBlockers: ["payment provider", "tax handling", "shipping cost", "order confirmation", "refund flow"],
    nextPass: "Keep checkout route blocked with launch-control UI until provider checkout, tax, shipping, order state and refunds are verified.",
  },
  {
    id: "vlm-token",
    route: "/[locale]/vlm-token",
    title: "VLM token / access layer",
    area: "vlm",
    progress: 54,
    status: "partial",
    vercelRisk: "medium",
    userGoal: "Understand VLM as utility/access, not investment, yield or price-promise.",
    currentState: "Utility wording is improving; session gating and final legal copy remain blockers.",
    launchBlockers: ["no ROI language review", "wallet/session gating", "token agreement", "risk copy"],
    nextPass: "Audit every VLM page for utility-only wording and remove any sentence that sounds like investment promotion.",
  },
  {
    id: "vlm-token-faq",
    route: "/[locale]/vlm-token/faq",
    title: "VLM token FAQ",
    area: "vlm",
    progress: 48,
    status: "partial",
    vercelRisk: "medium",
    userGoal: "Answer common questions without implying guaranteed access, profit, custody or investment safety.",
    currentState: "FAQ route exists; copy needs full PL/EN/DE consistency and legal-safe wording.",
    launchBlockers: ["complete translations", "legal wording", "no investment advice", "wallet safety"],
    nextPass: "Rewrite FAQ as plain-language safety + utility access guide.",
  },
  {
    id: "square",
    route: "/[locale]/square",
    title: "Velmère Square",
    area: "community",
    progress: 43,
    status: "partial",
    vercelRisk: "medium",
    userGoal: "Understand the community/product layer without confusing it with trading or investment claims.",
    currentState: "Square route exists, but product modules, moderation rules and member utility need definition.",
    launchBlockers: ["community rules", "moderation", "member utility", "content safety", "clear CTA"],
    nextPass: "Define Square as community + private digital layer: what users can do, what is blocked and what is coming later.",
  },
  {
    id: "community",
    route: "/[locale]/community",
    title: "Community",
    area: "community",
    progress: 42,
    status: "partial",
    vercelRisk: "low",
    userGoal: "Learn how to join or follow Velmère without unclear promises.",
    currentState: "Community shell exists, but launch content and moderation policy are still thin.",
    launchBlockers: ["moderation policy", "community CTA", "safe content rules"],
    nextPass: "Connect community page with Square and keep CTA simple.",
  },
  {
    id: "shield-table",
    route: "/[locale]/market-integrity",
    title: "Velmère Shield market table",
    area: "shield",
    progress: 91,
    status: "solid",
    vercelRisk: "medium",
    userGoal: "Find tokens, see logo-backed suggestions, sort anomalies and open a risk terminal with clickable VLM brain tiles without fake certainty.",
    currentState: "PASS168 keeps token avatars/source badges, adds a minimal VLM brain HUD, clickable static evidence board, slower Advanced Orbit 360 and darker detail drawer.",
    launchBlockers: ["holder API", "orderbook API", "contract checks", "rate limits", "mobile table real-device QA", "search logo verification"],
    nextPass: "Confirm search suggestion logos, real browser FPS, stronger source freshness labels and server-side rate/caching policy.",
  },
  {
    id: "shield-map",
    route: "/[locale]/market-integrity/shield-map",
    title: "Shield Map",
    area: "shield",
    progress: 65,
    status: "partial",
    vercelRisk: "medium",
    userGoal: "Understand the Shield operating model without exposing private scoring weights.",
    currentState: "Map explains workflow and source states; VLM brain cleanup improved terminal clarity but map copy still needs tightening and page length control.",
    launchBlockers: ["copy compression", "translation consistency", "source policy", "export policy"],
    nextPass: "Compress long sections into operator lanes and keep only one active explanation surface per scroll block.",
  },
  {
    id: "shield-about",
    route: "/[locale]/market-integrity/about",
    title: "Shield about / product explainer",
    area: "shield",
    progress: 50,
    status: "partial",
    vercelRisk: "low",
    userGoal: "Know what Shield does, what it does not do and how it avoids hype.",
    currentState: "Route exists; needs stronger public explanation of limitations and data modes.",
    launchBlockers: ["source limitations", "manual review language", "not advice wording"],
    nextPass: "Make the about page a short, clear product safety page.",
  },
  {
    id: "account-login",
    route: "/[locale]/account + /[locale]/login + aliases",
    title: "Account / login aliases",
    area: "account",
    progress: 45,
    status: "partial",
    vercelRisk: "medium",
    userGoal: "Sign in without duplicate-route confusion and without wallet seed-phrase risk.",
    currentState: "Many alias routes exist; they need canonical behavior and consistent copy.",
    launchBlockers: ["canonical redirect policy", "auth state", "wallet safety", "session copy"],
    nextPass: "Normalize account/login/konto/logowanie/signin/sign-in routes and prevent duplicate UX drift.",
  },
  {
    id: "member",
    route: "/[locale]/member",
    title: "Member / VLM access cockpit",
    area: "vlm",
    progress: 38,
    status: "blocked",
    vercelRisk: "medium",
    userGoal: "See access benefits only after safe session/member proof, without investment promise.",
    currentState: "Member route exists but production access gating is not wired.",
    launchBlockers: ["session gating", "wallet proof", "membership rules", "no ROI language"],
    nextPass: "Build utility-only member cockpit with blocked state before auth is production-ready.",
  },
  {
    id: "lookbook",
    route: "/[locale]/lookbook",
    title: "Lookbook",
    area: "brand",
    progress: 48,
    status: "partial",
    vercelRisk: "low",
    userGoal: "Feel the brand visually and move naturally to collection or Square.",
    currentState: "Route exists; final editorial assets and mobile rhythm are not launch-finished.",
    launchBlockers: ["final visuals", "mobile layout", "CTA path"],
    nextPass: "Make lookbook a premium brand page, not a placeholder gallery.",
  },
  {
    id: "research-lab",
    route: "/[locale]/research-lab",
    title: "Research Lab",
    area: "ops",
    progress: 36,
    status: "partial",
    vercelRisk: "medium",
    userGoal: "See experimental work without confusing it with proven scientific or investment claims.",
    currentState: "Route exists; needs strict boundary between experiments, claims and public product.",
    launchBlockers: ["claim safety", "source policy", "public wording", "legal review"],
    nextPass: "Label research as exploratory and keep crypto/investment/scientific claims conservative.",
  },
  {
    id: "legal-pages",
    route: "/[locale]/legal/* + privacy/terms/shipping/returns/impressum/contact/faq",
    title: "Legal and trust pages",
    area: "legal",
    progress: 72,
    status: "launch_control",
    vercelRisk: "low",
    userGoal: "Find seller identity, privacy, terms, shipping, returns and contact before checkout.",
    currentState: "Core pages exist; final legal verification and merchant identity confirmation remain required.",
    launchBlockers: ["final legal review", "merchant identity", "policy consistency", "localized copy"],
    nextPass: "Run legal text consistency pass across all language aliases and footer links.",
  },
  {
    id: "payment-order-state",
    route: "/[locale]/checkout + payment/webhook/order ops",
    title: "Payment / order state",
    area: "ops",
    progress: 28,
    status: "blocked",
    vercelRisk: "high",
    userGoal: "Complete payment only when provider, tax, order state, webhooks, receipts and refunds are production wired.",
    currentState: "Payment/order readiness matrix and order event ledger exist; real provider, database, signed webhook and email systems remain blocked.",
    launchBlockers: ["payment provider", "tax engine", "order database", "signed webhooks", "refund state", "transactional email"],
    nextPass: "Persist order event ledger, idempotency key store and signed webhook state behind environment gates.",
  },
  {
    id: "order-event-ledger",
    route: "/[locale]/checkout + webhook/order audit trail",
    title: "Order event ledger",
    area: "ops",
    progress: 21,
    status: "blocked",
    vercelRisk: "high",
    userGoal: "Trace every checkout, payment, refund and fulfillment event without duplicate or lost state.",
    currentState: "Order event ledger model and UI exist; persistent storage, idempotency store and signed provider webhooks are still blocked.",
    launchBlockers: ["event storage", "idempotency key store", "signed webhook verification", "retry queue", "order timeline", "support handoff"],
    nextPass: "Add persistent event envelope storage and provider webhook signature verification.",
  },
  {
    id: "admin-import",
    route: "/[locale]/admin/import-products",
    title: "Admin import products",
    area: "ops",
    progress: 85,
    status: "blocked",
    vercelRisk: "high",
    userGoal: "Import products safely without exposing admin tooling to public traffic.",
    currentState: "Admin route gate matrix exists, locked admin surface exists, server auth contract, auth session guard, role/scope map, idempotency store contract, publish permission gate, secret redaction policy, mutation audit envelope, audit persistence contract, locked audit write API route, rollback context, support-safe timeline and customer-safe export boundary exist; real auth provider, server session reader and persistent storage remain blocked.",
    launchBlockers: ["admin auth", "route protection", "environment checks", "import audit logs"],
    nextPass: "Choose auth provider, implement server session middleware and create persistent idempotency/audit storage adapters.",
  },
];

export const velmereCriticalPageBlockers = velmereSitePageAudit.filter((page) => page.status === "blocked" || page.vercelRisk === "high");

export const velmereSitePageAuditSummary = {
  totalPages: velmereSitePageAudit.length,
  averageProgress: Math.round(velmereSitePageAudit.reduce((sum, page) => sum + page.progress, 0) / velmereSitePageAudit.length),
  blockedPages: velmereSitePageAudit.filter((page) => page.status === "blocked").length,
  highVercelRiskPages: velmereSitePageAudit.filter((page) => page.vercelRisk === "high").length,
};

// PASS149 market-integrity state: Advanced-only Orbit guard, stronger tile explainer, darker selected tile panel and logo-aware search suggestions are wired; real Vercel build/browser check still required.

// PASS150 market-integrity state: Advanced brain gained Performance/Cinematic runtime governor, sparse React orbit frames, compositor transitions and auto-downgrade from Cinematic to Performance under slow frames.

// PASS168 market-integrity state: minimal VLM brain HUD, static evidence board, slower Orbit 360, clickable cards, source/logos preserved and debug copy removed.
